%YAML:1.0
# camera intrinsics
Dataset: "KITTI"

Camera.width: 1241
Camera.height: 376

Camera1.fx: 718.856
Camera1.fy: 718.856
Camera1.cx: 607.1928
Camera1.cy: 185.2157

Camera2.fx: 718.856
Camera2.fy: 718.856
Camera2.cx: 607.1928
Camera2.cy: 185.2157

Stereo.b: 0.53716

num_features: 150
num_features_init: 50
num_features_tracking: 50
num_features_tracking_bad: 20